### ISSUE TITLE
Error in building: Error in joblib

### ISSUE THREAD

**Issue by lbhnsh** [akdasUAF/ForestFireDetection#24]
'''
Found 0 images belonging to 2 classes.
Found 0 images belonging to 2 classes.
Traceback (most recent call last):
  File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 33, in <module>
    sys.exit(main())
  File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 28, in main
    pipeline = DBN_import_model('./Models/weights/dbn_pipeline_model.joblib')
  File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 13, in DBN_import_model
    loaded_pipeline = load(model_filename)
  File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
KeyError: 118
'''

I think it is some issue with joblib and the python version
although im using python 3.10 and only pip installed requirements.txt

**Comment by Dhruv16S** [comment]
> ```
> Found 0 images belonging to 2 classes.
> Found 0 images belonging to 2 classes.
> Traceback (most recent call last):
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 33, in <module>
>     sys.exit(main())
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 28, in main
>     pipeline = DBN_import_model('./Models/weights/dbn_pipeline_model.joblib')
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 13, in DBN_import_model
>     loaded_pipeline = load(model_filename)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
>     obj = _unpickle(fobj, filename, mmap_mode)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
>     obj = unpickler.load()
>   File "/usr/lib/python3.10/pickle.py", line 1213, in load
>     dispatch[key[0]](self)
> KeyError: 118
> ```
> 
> I think it is some issue with joblib and the python version although im using python 3.10 and only pip installed requirements.txt

Hey there. I have encountered a similar problem. Most of the problems I have read about this issue seem to happen when the version of joblib differs while dumping and loading a model. So, since we are installing the latest version of joblib and not the target version that was used while dumping, we get that problem.

**Comment by lbhnsh** [comment]
@Dhruv16S so did you figure out the error now, because im still stuck

**Comment by Dhruv16S** [comment]
> @Dhruv16S so did you figure out the error now, because im still stuck

Not yet, I am still trying to figure it out. For now, I have commented the lines of code in app.py where DBN is invoked

**Comment by staru09** [comment]
> ```
> Found 0 images belonging to 2 classes.
> Found 0 images belonging to 2 classes.
> Traceback (most recent call last):
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 33, in <module>
>     sys.exit(main())
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 28, in main
>     pipeline = DBN_import_model('./Models/weights/dbn_pipeline_model.joblib')
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 13, in DBN_import_model
>     loaded_pipeline = load(model_filename)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
>     obj = _unpickle(fobj, filename, mmap_mode)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
>     obj = unpickler.load()
>   File "/usr/lib/python3.10/pickle.py", line 1213, in load
>     dispatch[key[0]](self)
> KeyError: 118
> ```
> 
> I think it is some issue with joblib and the python version although im using python 3.10 and only pip installed requirements.txt

Just make sure that the model you are trying to use exist with proper weights in the desired location
Secondly see the dependencies and install them accordingly.

**Comment by YaliWang2019** [comment]
> ```
> Found 0 images belonging to 2 classes.
> Found 0 images belonging to 2 classes.
> Traceback (most recent call last):
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 33, in <module>
>     sys.exit(main())
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 28, in main
>     pipeline = DBN_import_model('./Models/weights/dbn_pipeline_model.joblib')
>   File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 13, in DBN_import_model
>     loaded_pipeline = load(model_filename)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
>     obj = _unpickle(fobj, filename, mmap_mode)
>   File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
>     obj = unpickler.load()
>   File "/usr/lib/python3.10/pickle.py", line 1213, in load
>     dispatch[key[0]](self)
> KeyError: 118
> ```
> 
> I think it is some issue with joblib and the python version although im using python 3.10 and only pip installed requirements.txt

Hi! I do believe that the error happened because when we git clone the repo locally, it didn’t really cloned the DBN models since they are too big and used up the free bandwidth of GitHub LFS service. Please refer to the Readme file for the update instructions on downloading the DBN model files. Thanks!
